import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "udir-green": {
          DEFAULT: "#76C69D",
          1: "#EEF8F3",
          2: "#DDF1E7",
          3: "#CCEADA",
          4: "#BBE3CE",
          5: "#A9DBC2",
          6: "#9BD8B9",
          7: "#76C69D",
          8: "#5BA27E",
          9: "#254B38",
          10: "#112E1F",
        },
        "udir-sort": {
          DEFAULT: "#303030",
          white: "#FFFFFF",
          1: "#FBFBFB",
          2: "#F4F4F4",
          3: "#EAEAEA",
          4: "#DEDEDE",
          5: "#C4C4C4",
          6: "#A0A0A0",
          7: "#757575",
          8: "#3D4146",
          9: "#303030",
        },
        "udir-blue": {
          DEFAULT: "#BED5E8",
          1: "#EFF7FE",
          2: "#E0EFFB",
          3: "#D3E6F6",
          4: "#C8DEF0",
          5: "#BED5E8",
          6: "#A9C0D3",
          7: "#7F99AE",
          8: "#6D889D",
          9: "#536D81",
          10: "#2F4960",
          11: "#263745",
          12: "#191D24",
        },
        "udir-brown": {
          DEFAULT: "#E5CEAE",
          1: "#FBF7F1",
          2: "#FBF3E8",
          3: "#F2E8DA",
          4: "#ECDBC2",
          5: "#E5CEAE",
          6: "#D6B689",
          7: "#BFA687",
          8: "#937A57",
          9: "#705C40",
          10: "#5E4521",
          11: "#261F14",
        },
        // Backward-compatible alias for existing utility classes.
        petrol: {
          DEFAULT: "#5BA27E",
          50: "#EEF8F3",
          100: "#DDF1E7",
          200: "#CCEADA",
          300: "#BBE3CE",
          400: "#A9DBC2",
          500: "#9BD8B9",
          600: "#76C69D",
          700: "#5BA27E",
          800: "#254B38",
          900: "#112E1F",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-out-right": "slide-out-right 0.3s ease-in",
        "fade-in": "fade-in 0.2s ease-in",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
